name: CI

on:
  pull_request:
    branches:
      - main

jobs:
  Build-the-Application:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Job Triggered"
      - run: echo "🔎 The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."

      - name: Checkout the Repository Code
        uses: actions/checkout@v4
      - run: echo "Repository has been cloned to the Runner"

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install Dependencies
        run: npm install

      - name: Build the Application
        run: npm run build